### ISSUE TITLE
## Search Command

### ISSUE THREAD

**Issue by madeyoga** [nano-devs/Musicfy-Bot#25]
Search song command does not work

**Comment by madeyoga** [comment]
@Shiroechi 
https://github.com/Shiroechi/YouTubeSearchApi-Java/blob/ab8cc0f89283bdb7eabb7905e7496cc0737a3a8a/src/main/java/YouTubeSearchApi/utility/Utils.java#L24-L25

**Comment by Shiroechi** [comment]
done
