### ISSUE TITLE
## Play Url Command Add History

### ISSUE THREAD

**Issue by madeyoga** [nano-devs/Musicfy-Bot#26]
Empty title

**Comment by Shiroechi** [comment]
You can get the title from no embed first or just pass the empty string again.

In my newest pull request i have add a chek for empty title, if title is empty get the title from no embed

**Comment by madeyoga** [comment]
Will be fixed at the next major update including 
- PlayUrl Command
- Play Command
- Search Command
- PlayUserPlaylist Command
- PlayGuildPlaylist Command
