### ISSUE TITLE
Play User Playlist

### ISSUE THREAD

**Issue by madeyoga** [nano-devs/Musicfy-Bot#31]
there's no response if the music is longer tahn 15 minutes.

**Comment by Shiroechi** [comment]
maybe its impossible

**Comment by Shiroechi** [comment]
There's a trick, but not recommend it.
Before add the track to queue, check the length before using Youtubeclient or noembed to get the length

**Comment by madeyoga** [comment]
> There's a trick, but not recommend it.
> Before add the track to queue, check the length before using Youtubeclient or noembed to get the length

This will only work for youtube url

**Comment by madeyoga** [comment]
## Solution 1
What about just check queue length before and after the `AddPlaylistTrack` process. 
```java
if (beforeQueueLength != afterQueueLength) {
    // Notify user the length difference and put foot note
   // Foot note: "Only track(s) with duration less than 15minutes are added to queue."
}
```

## Solution 2
Make the case never happen,

Check the track duration before its added to the playlist.
